secrets:
  GITHUB_TOKEN: GITHUB_TOKEN
  BUILDKITE_API_TOKEN: API_TOKEN_BUILDKITE
  LINEAR_API_TOKEN: LINEAR_API_TOKEN

env:
  GITHUB_CLI_VERSION: "2.83.0"
  LINEAR_CLI_VERSION: "latest"
  BUILDKITE_MCP_SERVER_VERSION: "0.7.3"
  TRIGGER_ON_LABEL: "buildkite-analyze"
  MODEL_PROVIDER: "anthropic"

steps:
  - label: ":node: Generate the pipeline"
    command: |
      if [[ "${BUILDKITE_SOURCE:-}" != "webhook" || -z "${BUILDKITE_TRIGGER_ID:-}" ]]; then
        echo "Not a webhook trigger -- exiting."
        exit 0
      fi

      # Generate and upload the pipeline to handle the webhook.
      echo "--- :webhook: Run the webhook handler"
      npm ci && npm run build
      node dist/handler
